apiVersion: apps/v1
kind: Deployment
metadata:
  name: go

spec:
  replicas: 2

  selector:
    matchLabels:
      app: go

  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: everaldofilho/servergo:latest
          ports:
            - containerPort: 3000