apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP #ou LoadBalancer
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
  selector:
    app: nginx-deployment